;;;; Implement a data store for a session.

(defstruct sessiondata
    domains ; A DomainStore intstance of one, or more, domains.
    needs   ; A NeedStore of needs generated by domains.
    can-do  ; A NeedStore of needs that can be done.
    cant-do ; A NeedStore of needs that cannot be done.
)
; Functions automatically created by defstruct:
;
; Most used:
;   (sessiondata-<field name> <instance>) -> struct field.
;   (sessiondata-p <instance>) -> bool
;
; Least used:
;   (type-of <instance>) -> sessiondata
;   (typep <instance> 'sessiondata) -> bool
;
; Probably shouldn't use:
;   (make-sessiondata [:<field-name> <field-sessiondata>]*), use sessiondata-new instead.
;   (copy-sessiondata <instance>) copies a sessiondata instance.

(defun sessiondata-new () ; -> sessiondata
    (make-sessiondata :domains (domainstore-new) :needs (needstore-new nil) :can-do (needstore-new nil) :cant-do (needstore-new nil))
)

;;; Return a string representation of a sessiondata instance.
(defun sessiondata-str (sessx)  ; -> string.                                                                      
  (assert (sessiondata-p sessx))

    (let ((strs "#S(SESSIONDATA "))
      (setf strs (concatenate 'string strs (domainstore-str (sessiondata-domains sessx))))

      (setf strs (concatenate 'string strs ")"))

      strs
    )
) 

;;; Print sessiondata.
(defun sessiondata-print (sessx)
  (assert (sessiondata-p sessx))

  (domainstore-print (sessiondata-domains sessx))
)

;;; Return a sessiondata instance, given a list of symbols.
(defun sessiondata-from (symbols) ; -> sessiondata instance.
    ;(format t "~&sessiondata-from: ~A" (type-of symbols))
    (assert (listp symbols))
    (assert (not (null symbols)))
    (assert (typep (car symbols) 'SYMBOL))
    (assert (eq (car symbols) 'SD))
    
    (let (sdx key ds sr sc rest-symbols)
        (cond ((string= (symbol-name (car symbols)) "SD")
                (setf rest-symbols (cdr symbols))
                ;(format t "~&sessiondata-from4 ~A ~A" (type-of rest-symbols) rest-symbols)

                ; Process tokens, get domainstore.
                (loop for tokx in rest-symbols do
                    (setf key (symbol-name (car tokx)))
                    ;(format t "~&sessiondata-from: tokx: ~A" tokx)
                    (when (string= key "DS") ; Must be just one domainstore.
                           ;(format t "~&sessiondata-from: ds: ~A" tokx)
                           (assert (null ds)) ; only one ds allowed.
                           (setf ds (domainstore-from tokx))
                           (if ds
                               ;(session-data :domains ds)
                               nil)
                     )
                )
                (assert ds) ; one ds required.

                ;; Stort sessiondata.
                (setf sdx (make-sessiondata :domains ds))

                ;; Get select regions and statescorr, if any.
                (loop for tokx in rest-symbols do
                    (setf key (symbol-name (car tokx)))
                    (cond ((string= key "SR") ; Can be zero, or more, selectregions.
                           ;(format t "~&sessiondata-from: sr: ~A" tokx)
                       (setf sr (selectregions-from tokx))
                       ;(if sr
                       ;    (format t "~&sessiondata: sr is ~A" (selectregions-str sr))
                       ;    nil)
                       )
                      ((string= key "SC") ; Must be zero, or one, statescorr.
                       ;(format t "~&sessiondata-from: sc: ~A" tokx)
                       (setf sc (statescorr-from tokx))
                       ;(if sc
                       ;    (format t "~&sessiondata: sc is ~A" (statescorr-str sc))
                       ;    nil)
                       )
                      (t nil)
                    )
                )

                ;; Return sessiondata instance.
                sdx
              )
              (t (error "SD symbol missing")))
     )
)

;;; Return current needs.
(defun sessiondata-get-needs (sessx) ; -> (values can-do cant-do)
  ;(format t "~&sessiondata-get-needs ~A" (type-of sessx))
  (assert (sessiondata-p sessx))

  (multiple-value-bind (needs can-do cant-do)
      (domainstore-get-needs (sessiondata-domains sessx))
      (setf (sessiondata-needs sessx) needs)
      (setf (sessiondata-can-do sessx) can-do)
      (setf (sessiondata-cant-do sessx) cant-do)
  )
)

;;; Process a given need.
(defun sessiondata-process-need (sessx nedx)
  ;(format t "~&sessiondata-process-need: ~A ~A" (type-of sessx) (type-of nedx))
  (assert (sessiondata-p sessx))
  (assert (need-p nedx))

  (domainstore-process-need (sessiondata-domains sessx) nedx)
)

